### ISSUE TITLE
[Question] Does this library support many-to-many polymorphic relation?

### ISSUE THREAD

**Issue by s4kh** [bashleigh/typeorm-polymorphic#13]
HI thanks for the library.

Does it support many-to-many polymorphic relation like tags <->videos, images? Tagging(Junction table) -> entityId, entityType, tagId something like this? If not, how would approach it? Do you prefer creating a custom junction table and use this library to have like OneTOMany from video, images -> Tagging <- Tags?

**Comment by bashleigh** [comment]
potentially yes? 

I haven't used or worked on this package now for a very long time. I know children relationships 100% work with hydration, creation and updating as that's what I built it for. I know parent relationships have an issue and I have attempted to correct but it got messy and my time was limited.

I reckon you should be able to use a 2 way child setup. Both parent and child decorators use the same methods so 2 children entities should work 🤞 

In your scenario however I don't think you'd need polymorphic relationships, you could quite easily have tags which relate separately to images and videos. However if you wanted to do the reverse where you fetched tags and the tag could relate to videos and images together. Then yes you would need polymorphic relationships setup in a custom many-to-many table. I usually make a custom entity for this type of setup so I can define different properties in the joiner table for queries. 

```ts
export class TagEntity {
  @OneToMany(() => TagPolymorphicEntity, source => source.tag)
  source: TagPolymorphicEntity;
  
  @Column()
  name: string;
}

export class TagPolymorphicEntity {

  @PolymorphicParent(() => [VideoEntity, ImageEntity], {
    eager: false,
  })
  resource: VideoEntity | ImageEntity;
  
  @OneToMany(() => TagEntity, tag => tag.source)
  tag: TagEntity;

}

export class VideoEntity {

  @PolymorphicParent(() => TagPolymorphicEntity, {
    eager: false,
  })
  tagSource: TagPolymorphicEntity;
}
    
```

This is sort of what you want? I'm not sure if the correct decorator was children or parent but this should work 🤞 

Also you might not like this example so you could make the `TagPolymorphicEntity` a JoinTable definition instead. I just like it so I can explicitly get properties and joins etc like so `video.tagSource.tag.name` and so on.

Let me know if this works! It's not the best library in the world and it definately wasn't finished!

**Comment by s4kh** [comment]
First of all, thanks for the response. I have to use the repository in order to make the decorators we are using nestjs-graphql where we don't use repository at all. I think it does it under the hood.

**Comment by bashleigh** [comment]
Ah then I think it'll be a bit difficult as this package uses a custom repository to resolve the relatipnships
