### ISSUE TITLE
Entity does not have a primary column.

### ISSUE THREAD

**Issue by MadRoosterCro** [bashleigh/typeorm-polymorphic#17]
Hello there! I followed along, but ran into a hiccup. 

The console says "Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity."

I noticed you do not use that decorator on your child entity, so I did the same thing and this issue came up. How did you tackle it?

**Comment by bashleigh** [comment]
Hey! I used the auto generated one instead! 

```ts
  @PrimaryGeneratedColumn()
  id: number;
  ```
  
  I probably left it out of the other examples!
