### ISSUE TITLE
Where is version 0.0.10?

### ISSUE THREAD

**Issue by kapitanluffy** [bashleigh/typeorm-polymorphic#30]
I was checking out the repo in npm and it says the latest version is `0.0.10`. I cannot see it in the repo though

![image](https://user-images.githubusercontent.com/485799/189512964-4f85304e-6d22-4f3c-aaf1-810385b9d52d.png)

**Comment by bashleigh** [comment]
There was a version 10? :| must've made a mistake there 😅 sorry
